#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
set +x # Never trace credential input, even when started with bash -x.
umask 077
PS_SOURCE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
PS_HELPER="$PS_SOURCE/scripts/setup-config.mjs"
PS_TEMP=$(mktemp -d "${TMPDIR:-/tmp}/pi-spoke-setup.XXXXXX")
ENV_FILE="$PS_TEMP/answers.env"
touch "$ENV_FILE"
trap 'rm -rf -- "$PS_TEMP"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
[[ -t 0 ]] || { say "Run bash install.sh from an interactive terminal."; exit 1; }

ask_value() {
  local key="$1" prompt="$2" fallback="${3:-}" value
  value=$(_existing "$key" || true)
  [[ -n "$value" ]] || value="$fallback"
  ask "$key" "$prompt${value:+ [$value]}:"
  [[ -n "${!key}" ]] || printf -v "$key" '%s' "$value"
  write_env "$key" "${!key}"
}

need_value() {
  local key="$1" prompt="$2" fallback="${3:-}"
  while :; do
    ask_value "$key" "$prompt" "$fallback"
    [[ -n "${!key}" ]] && break
    warn "A value is required. Ctrl-C exits without saving the configuration."
  done
}

choose() {
  local key="$1" prompt="$2" fallback="$3" choices="$4"
  while :; do
    need_value "$key" "$prompt" "$fallback"
    case " $choices " in *" ${!key} "*) return ;; esac
    warn "Choose one of: $choices"
  done
}

load_answers() {
  local key value
  while IFS='=' read -r key value; do
    [[ "$key" =~ ^PS_[A-Z_]+$ ]] || continue
    printf -v "$key" '%s' "$value"
  done < "$ENV_FILE"
}

printf '\n%s%s  Pi Spoke Installer%s\n' "$BOLD" "$BLUE" "$RESET"
say "Install → configure providers → set worker permissions → connect Codex."
say "You will review the files before saving. API-key input is hidden."
say "Configuration is saved at stage 7; an earlier cancellation discards answers."
pause "Press Enter to begin."

stage "Host prerequisites"
case "$(uname -s)/$(uname -m)" in
  Darwin/arm64) PS_PLATFORM=darwin; PS_ARCH=arm64 ;;
  Linux/aarch64|Linux/arm64) PS_PLATFORM=linux; PS_ARCH=arm64 ;;
  *) warn "The current release qualifies macOS and Linux arm64 only. See docs/compatibility.md."; exit 1 ;;
esac
say "Worker tools require the exact host/toolchain identities in docs/compatibility.md."
say "The sandbox check at stage 8 will report whether this host is ready."
PS_MISSING=()
for PS_COMMAND in curl tar gzip; do
  command -v "$PS_COMMAND" >/dev/null 2>&1 || PS_MISSING+=("$PS_COMMAND")
done
if ! command -v shasum >/dev/null 2>&1 && ! command -v sha256sum >/dev/null 2>&1; then PS_MISSING+=("shasum or sha256sum"); fi
if [[ "$PS_PLATFORM" == darwin ]]; then
  command -v rg >/dev/null 2>&1 || PS_MISSING+=(ripgrep)
  [[ -x /usr/bin/sandbox-exec ]] || PS_MISSING+=(sandbox-exec)
  if ! /usr/bin/xcrun --find clang >/dev/null 2>&1; then PS_MISSING+=("Xcode command-line tools"); fi
  if (( ${#PS_MISSING[@]} )); then
    warn "Missing: ${PS_MISSING[*]}"
    if ! /usr/bin/xcrun --find clang >/dev/null 2>&1; then
      if confirm "Open Apple's command-line tools installer?"; then /usr/bin/xcode-select --install; fi
      step "Complete Apple's installer, then rerun this setup."
    fi
    if ! command -v rg >/dev/null 2>&1; then
      if command -v brew >/dev/null 2>&1 && confirm "Install ripgrep with Homebrew?"; then brew install ripgrep; fi
      step "If ripgrep is still missing, install it with: brew install ripgrep"
    fi
  fi
else
  for PS_COMMAND in rg bwrap socat cc; do
    command -v "$PS_COMMAND" >/dev/null 2>&1 || PS_MISSING+=("$PS_COMMAND")
  done
  if (( ${#PS_MISSING[@]} )); then
    warn "Missing: ${PS_MISSING[*]}"
    if command -v apt-get >/dev/null 2>&1 && confirm "Install prerequisites using sudo apt-get?"; then
      sudo apt-get update
      sudo apt-get install -y curl ca-certificates tar gzip coreutils ripgrep bubblewrap socat build-essential
    else
      step "On Ubuntu, run: sudo apt-get update"
      step "Then: sudo apt-get install curl ca-certificates tar gzip coreutils ripgrep bubblewrap socat build-essential"
    fi
  fi
fi
if (( ${#PS_MISSING[@]} )); then
  PS_MISSING=()
  for PS_COMMAND in curl tar gzip rg; do command -v "$PS_COMMAND" >/dev/null 2>&1 || PS_MISSING+=("$PS_COMMAND"); done
  if ! command -v shasum >/dev/null 2>&1 && ! command -v sha256sum >/dev/null 2>&1; then PS_MISSING+=("SHA-256 utility"); fi
  if [[ "$PS_PLATFORM" == darwin ]]; then
    [[ -x /usr/bin/sandbox-exec ]] || PS_MISSING+=(sandbox-exec)
    /usr/bin/xcrun --find clang >/dev/null 2>&1 || PS_MISSING+=("Xcode command-line tools")
  else
    for PS_COMMAND in bwrap socat cc; do command -v "$PS_COMMAND" >/dev/null 2>&1 || PS_MISSING+=("$PS_COMMAND"); done
  fi
  if (( ${#PS_MISSING[@]} )); then warn "Still missing: ${PS_MISSING[*]}. Install them and rerun."; exit 1; fi
fi
pause "Prerequisites found. Press Enter to choose the installation."

stage "Private Node and pi-spoke installation"
PS_BASE="$HOME/.local/share/pi-spoke"
PS_NODE_DEFAULT="$PS_BASE/node-v24.15.0/bin/node"
if [[ ! -x "$PS_NODE_DEFAULT" ]] && command -v node >/dev/null 2>&1; then
  if [[ "$(node --version)" == v24.15.0 ]]; then PS_NODE_DEFAULT=$(command -v node); fi
fi
ask_value PS_NODE "Node 24.15.0 binary (missing default can be installed)" "$PS_NODE_DEFAULT"
if [[ ! -x "$PS_NODE" ]]; then
  [[ "$PS_NODE" == "$PS_BASE/node-v24.15.0/bin/node" ]] || { warn "Choose an existing Node binary or the offered install path."; exit 1; }
  [[ ! -e "$PS_BASE/node-v24.15.0" && ! -L "$PS_BASE/node-v24.15.0" ]] || { warn "Node install directory exists but is incomplete; select another existing binary."; exit 1; }
  confirm "Download Node 24.15.0 from nodejs.org into $PS_BASE/node-v24.15.0?" || exit 0
  PS_ARCHIVE="node-v24.15.0-$PS_PLATFORM-$PS_ARCH.tar.gz"
  curl --proto '=https' --tlsv1.2 --fail --location --show-error "https://nodejs.org/dist/v24.15.0/$PS_ARCHIVE" -o "$PS_TEMP/$PS_ARCHIVE"
  curl --proto '=https' --tlsv1.2 --fail --location --show-error "https://nodejs.org/dist/v24.15.0/SHASUMS256.txt" -o "$PS_TEMP/SHASUMS256.txt"
  PS_EXPECTED=$(awk -v name="$PS_ARCHIVE" '$2 == name {print $1}' "$PS_TEMP/SHASUMS256.txt")
  [[ "$PS_EXPECTED" =~ ^[a-f0-9]{64}$ ]] || { warn "No checksum found for the Node archive."; exit 1; }
  if command -v shasum >/dev/null 2>&1; then PS_ACTUAL=$(shasum -a 256 "$PS_TEMP/$PS_ARCHIVE"); else PS_ACTUAL=$(sha256sum "$PS_TEMP/$PS_ARCHIVE"); fi
  [[ "${PS_ACTUAL%% *}" == "$PS_EXPECTED" ]] || { warn "Node archive checksum mismatch."; exit 1; }
  mkdir -p "$PS_BASE"
  PS_NODE_STAGE=$(mktemp -d "$PS_BASE/.node-install.XXXXXX")
  # Extract beside the final path so activation is one rename on the same filesystem.
  if ! tar -xzf "$PS_TEMP/$PS_ARCHIVE" -C "$PS_NODE_STAGE" --strip-components=1; then
    rm -rf -- "$PS_NODE_STAGE"; exit 1
  fi
  mv "$PS_NODE_STAGE" "$PS_BASE/node-v24.15.0"
fi
[[ "$("$PS_NODE" --version)" == v24.15.0 ]] || { warn "Use the qualified Node version 24.15.0."; exit 1; }
PS_NODE=$("$PS_NODE" -p 'process.execPath')
write_env PS_NODE "$PS_NODE"
export PATH="$(dirname -- "$PS_NODE"):$PATH"
PS_RUNTIME_DEFAULT="$PS_BASE/current"
if [[ ! -f "$PS_RUNTIME_DEFAULT/dist/cli.js" ]]; then PS_RUNTIME_DEFAULT="$PS_BASE/install-$(date +%Y%m%d-%H%M%S)"; fi
ask_value PS_RUNTIME "Installation directory (existing build, or a new directory)" "$PS_RUNTIME_DEFAULT"
[[ "$PS_RUNTIME" == /* ]] || { warn "Use an absolute installation path."; exit 1; }
if [[ -f "$PS_RUNTIME/dist/cli.js" && -d "$PS_RUNTIME/node_modules" ]]; then
  say "Using the existing installation: $PS_RUNTIME"
else
  say "This copies the source and builds with locked dependencies."
  confirm "Install pi-spoke into $PS_RUNTIME using npm ci --ignore-scripts and npm run build?" || exit 0
  mkdir -p "$(dirname -- "$PS_RUNTIME")"
  "$PS_NODE" "$PS_HELPER" install "$PS_SOURCE" "$PS_RUNTIME"
  PS_NPM="$(dirname -- "$PS_NODE")/npm"
  [[ -x "$PS_NPM" ]] || { warn "npm must be installed beside the selected Node binary."; exit 1; }
  (cd -- "$PS_RUNTIME" && "$PS_NPM" ci --ignore-scripts && "$PS_NPM" run build)
fi
pause "Installation selected. Press Enter to configure it."

stage "Configuration and workspace paths"
say "Keep the installation, configuration, state, and scratch outside worker workspaces."
ask_value PS_CONFIG_DIR "Configuration directory" "$HOME/.config/pi-spoke"
[[ "$PS_CONFIG_DIR" == /* ]] || { warn "Use an absolute configuration path."; exit 1; }
cp "$ENV_FILE" "$PS_TEMP/install.env"
"$PS_NODE" "$PS_HELPER" defaults "$PS_CONFIG_DIR" "$ENV_FILE"
cat "$PS_TEMP/install.env" >> "$ENV_FILE"
load_answers
if [[ -f "$PS_CONFIG_DIR/config.json" ]]; then
  say "Existing settings are used as defaults; additional workspaces and allowed models are retained."
  say "Stop this pi-spoke MCP instance before changing its configuration, then restart it after setup."
fi
need_value PS_WORKSPACE "Existing workspace directory workers may read"
ask_value PS_STATE_DIR "Private state directory" "$HOME/.local/share/pi-spoke/state"
ask_value PS_SCRATCH_DIR "Private scratch directory (keep this path short)" "$HOME/.ps-tmp"
ask_value PS_INSTANCE "MCP instance name" codex

stage "Pi credentials"
say "auth.json stores provider credentials. models.json describes provider endpoints and models."
say "config.json controls the pi-spoke worker permissions and limits."
choose PS_AUTH_MODE "Reuse existing Pi files, or create new provider files? (reuse/new)" new "reuse new"
if [[ "$PS_AUTH_MODE" == reuse ]]; then
  step "Use the auth.json created by Pi's /login, or your operator-managed credential file."
  need_value PS_AUTH_PATH "Existing auth.json path" "$HOME/.pi/agent/auth.json"
  say "For built-in models, models.json is optional. Enter '-' to omit it."
  ask_value PS_MODELS_PATH "Existing models.json path, or '-'" -
  [[ "$PS_MODELS_PATH" != - ]] || { PS_MODELS_PATH=""; write_env PS_MODELS_PATH ""; }
else
  say "Creates auth.json and models.json inside $PS_CONFIG_DIR. Existing provider files are never replaced."
  step "Open your provider's account dashboard and obtain an API key. The exact menu varies by provider."
  ask_value PS_DASHBOARD "Provider dashboard URL to open, or '-'" -
  if [[ "$PS_DASHBOARD" != - ]]; then
    case "$PS_DASHBOARD" in https://*) open_url "$PS_DASHBOARD" ;; *) warn "Use an HTTPS dashboard URL."; exit 1 ;; esac
  fi
  step "Copy the provider's API key. For a keyless local server, enter its documented placeholder key."
  while :; do
    ask_secret PS_KEY "Paste the API key (hidden):"
    [[ -n "$PS_KEY" ]] && break
    warn "An API key or local-server placeholder is required."
  done
  write_env PS_KEY "$PS_KEY"
  unset PS_KEY
fi

stage "Provider and model"
step "Copy the exact provider name and model ID from your Pi configuration or provider documentation."
need_value PS_PROVIDER "Provider ID (for a new custom provider, choose a unique name)"
need_value PS_MODEL "Model ID"
ask_value PS_DESCRIPTION "Optional model description (enter '-' to clear)"
[[ "$PS_DESCRIPTION" != - ]] || { PS_DESCRIPTION=""; write_env PS_DESCRIPTION ""; }
if [[ "$PS_AUTH_MODE" == new ]]; then
  need_value PS_BASE_URL "Provider API base URL (include /v1 when required)"
  choose PS_API "API protocol" openai-completions "openai-completions openai-responses anthropic-messages google-generative-ai"
  say "Enter the model's documented limits; the offered values are Pi defaults."
  ask_value PS_CONTEXT "Context window in tokens" 128000
  ask_value PS_OUTPUT "Maximum output tokens" 16384
  choose PS_REASONING "Model supports reasoning? (yes/no)" no "yes no"
  choose PS_VISION "Model supports image input? (yes/no)" no "yes no"
fi

stage "Worker permissions and limits"
say "read: read/search only. edit: read/search plus structured edits in one explicit directory."
say "keep: retain the existing tool and write policy. read/edit replace that policy."
choose PS_PERMISSION_MODE "Permission policy (read/edit/keep)" read "read edit keep"
if [[ "$PS_PERMISSION_MODE" == edit ]]; then
  say "Each worker must still request a narrower file-write scope when it starts."
  need_value PS_FILE_ROOT "Existing directory where file edits may be granted" "$PS_WORKSPACE"
fi
say "Tool networking stays disabled. Existing skill settings are retained; new setups disable skills."
ask_value PS_WALL_MS "Maximum run duration in milliseconds" 180000
ask_value PS_TURNS "Maximum turns per run" 12
ask_value PS_ACTIVE "Maximum simultaneous runs" 3

stage "Review and save"
"$PS_NODE" "$PS_HELPER" prepare "$ENV_FILE" "$PS_TEMP"
say "Provider files are validated without resolving credentials or contacting providers."
confirm "Save the displayed configuration and connection snippet, backing up files marked for replacement?" || exit 0
"$PS_NODE" "$PS_HELPER" save "$PS_TEMP/plan.json"
PS_CONFIG_PATH="$PS_CONFIG_DIR/config.json"
pause "Saved. Press Enter to check the MCP server."

stage "Verify host and MCP server"
"$PS_NODE" "$PS_RUNTIME/dist/cli.js" doctor --config "$PS_CONFIG_PATH" --instance "$PS_INSTANCE"
say "The sandbox check runs disposable canaries. The MCP check starts and stops the server and lists its six tools."
say "These checks make no inference requests. Stop an existing server using this instance before checking MCP."
PS_CHECKS_OK=yes
if confirm "Run the sandbox canaries and MCP handshake now?"; then
  if ! "$PS_NODE" "$PS_RUNTIME/dist/cli.js" doctor --config "$PS_CONFIG_PATH" --instance "$PS_INSTANCE" --sandbox-check; then
    PS_CHECKS_OK=no
    SKIPPED+=("Sandbox verification failed; inspect docs/compatibility.md before running workers.")
  fi
  if ! "$PS_NODE" "$PS_HELPER" check "$PS_TEMP/plan.json"; then
    PS_CHECKS_OK=no
    SKIPPED+=("MCP handshake failed; stop any existing instance, inspect configuration, and retry.")
  fi
else
  PS_CHECKS_OK=no
  SKIPPED+=("Sandbox and MCP verification were skipped.")
fi
pause "Press Enter for the host connection."

stage "Connect to Codex"
PS_CODEX=$(command -v codex || true)
if [[ -z "$PS_CODEX" && -x /Applications/ChatGPT.app/Contents/Resources/codex ]]; then PS_CODEX=/Applications/ChatGPT.app/Contents/Resources/codex; fi
say "Connection snippet: $PS_CONFIG_DIR/codex.toml"
say "Other MCP hosts can use the same command and arguments shown in that file."
if [[ -n "$PS_CODEX" && "$PS_CHECKS_OK" == yes ]] && confirm "Register pi_spoke in Codex now (replaces its existing entry if present)?"; then
  PS_CODEX_CONFIG="${CODEX_HOME:-$HOME/.codex}/config.toml"
  if [[ -f "$PS_CODEX_CONFIG" ]]; then
    PS_CODEX_BACKUP=$(mktemp "$PS_CODEX_CONFIG.backup-XXXXXX")
    cat "$PS_CODEX_CONFIG" > "$PS_CODEX_BACKUP"
    say "Codex configuration backup: $PS_CODEX_BACKUP"
  fi
  "$PS_CODEX" mcp add pi_spoke -- "$PS_NODE" "$PS_RUNTIME/dist/cli.js" serve --config "$PS_CONFIG_PATH" --instance "$PS_INSTANCE"
  say "Codex registration saved. Restart Codex to load the MCP connection."
else
  step "After verification, merge the [mcp_servers.pi_spoke] section from the snippet into your Codex config.toml."
  step "Replace an existing pi_spoke section; do not append a duplicate. Restart Codex afterward."
  SKIPPED+=("Codex registration: use the generated codex.toml snippet after verification.")
fi
say "Installed runtime: $PS_RUNTIME"
say "Operator configuration: $PS_CONFIG_PATH"
say "To adjust the setup later, rerun this installer and select the same installation/configuration paths."
if (( ${#SKIPPED[@]} )); then
  warn "Setup saved with remaining steps:"
  for PS_ITEM in "${SKIPPED[@]}"; do say "$PS_ITEM"; done
else
  say "Setup complete. Sandbox and MCP checks passed; provider entitlement has not been tested."
fi
