#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3
set +x
umask 077
PS_SOURCE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
PS_HELPER="$PS_SOURCE/scripts/setup-config.mjs"
PS_TEMP=$(mktemp -d "${TMPDIR:-/tmp}/pi-spoke-setup.XXXXXX")
ENV_FILE="$PS_TEMP/answers.env"
touch "$ENV_FILE"
trap 'rm -rf -- "$PS_TEMP"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
[[ -t 0 ]] || { say "Run bash install.sh from an interactive terminal."; exit 1; }

load_answers() {
  local key value
  while IFS='=' read -r key value; do
    [[ "$key" =~ ^PS_[A-Z_]+$ ]] || continue
    printf -v "$key" '%s' "$value"
  done < "$ENV_FILE"
}

printf '\n%s%s  Pi Spoke Installer%s\n' "$BOLD" "$BLUE" "$RESET"
say "Install with defaults, choose a workspace, then connect Codex."
say "Model setup is documented in README.md → Model configuration."

stage "Install"
case "$(uname -s)/$(uname -m)" in
  Darwin/arm64) PS_PLATFORM=darwin; PS_ARCH=arm64 ;;
  Linux/aarch64|Linux/arm64) PS_PLATFORM=linux; PS_ARCH=arm64 ;;
  *) warn "The current release qualifies macOS and Linux arm64 only. See docs/compatibility.md."; exit 1 ;;
esac
say "Worker tools require the exact host/toolchain identities in docs/compatibility.md."
say "Sandbox readiness is checked automatically after configuration."
PS_MISSING=()
for PS_COMMAND in curl tar gzip; do
  command -v "$PS_COMMAND" >/dev/null 2>&1 || PS_MISSING+=("$PS_COMMAND")
done
if ! command -v shasum >/dev/null 2>&1 && ! command -v sha256sum >/dev/null 2>&1; then PS_MISSING+=("shasum or sha256sum"); fi
if [[ "$PS_PLATFORM" == darwin ]]; then
  command -v rg >/dev/null 2>&1 || PS_MISSING+=(ripgrep)
  [[ -x /usr/bin/sandbox-exec ]] || PS_MISSING+=(sandbox-exec)
  if ! /usr/bin/xcrun --find clang >/dev/null 2>&1; then PS_MISSING+=("Xcode command-line tools"); fi
  if (( ${#PS_MISSING[@]} )); then
    warn "Missing: ${PS_MISSING[*]}"
    if ! /usr/bin/xcrun --find clang >/dev/null 2>&1; then
      if confirm "Open Apple's command-line tools installer?"; then /usr/bin/xcode-select --install; fi
      step "Complete Apple's installer, then rerun this setup."
    fi
    if ! command -v rg >/dev/null 2>&1; then
      if command -v brew >/dev/null 2>&1 && confirm "Install ripgrep with Homebrew?"; then brew install ripgrep; fi
      step "If ripgrep is still missing, install it with: brew install ripgrep"
    fi
  fi
else
  for PS_COMMAND in rg bwrap socat cc; do
    command -v "$PS_COMMAND" >/dev/null 2>&1 || PS_MISSING+=("$PS_COMMAND")
  done
  if (( ${#PS_MISSING[@]} )); then
    warn "Missing: ${PS_MISSING[*]}"
    if command -v apt-get >/dev/null 2>&1 && confirm "Install prerequisites using sudo apt-get?"; then
      sudo apt-get update
      sudo apt-get install -y curl ca-certificates tar gzip coreutils ripgrep bubblewrap socat build-essential
    else
      step "On Ubuntu, run: sudo apt-get update"
      step "Then: sudo apt-get install curl ca-certificates tar gzip coreutils ripgrep bubblewrap socat build-essential"
    fi
  fi
fi
if (( ${#PS_MISSING[@]} )); then
  PS_MISSING=()
  for PS_COMMAND in curl tar gzip rg; do command -v "$PS_COMMAND" >/dev/null 2>&1 || PS_MISSING+=("$PS_COMMAND"); done
  if ! command -v shasum >/dev/null 2>&1 && ! command -v sha256sum >/dev/null 2>&1; then PS_MISSING+=("SHA-256 utility"); fi
  if [[ "$PS_PLATFORM" == darwin ]]; then
    [[ -x /usr/bin/sandbox-exec ]] || PS_MISSING+=(sandbox-exec)
    /usr/bin/xcrun --find clang >/dev/null 2>&1 || PS_MISSING+=("Xcode command-line tools")
  else
    for PS_COMMAND in bwrap socat cc; do command -v "$PS_COMMAND" >/dev/null 2>&1 || PS_MISSING+=("$PS_COMMAND"); done
  fi
  if (( ${#PS_MISSING[@]} )); then warn "Still missing: ${PS_MISSING[*]}. Install them and rerun."; exit 1; fi
fi
PS_BASE="$HOME/.local/share/pi-spoke"
PS_NODE_DEFAULT="$PS_BASE/node-v24.15.0/bin/node"
if [[ ! -x "$PS_NODE_DEFAULT" ]] && command -v node >/dev/null 2>&1; then
  if [[ "$(node --version)" == v24.15.0 ]]; then PS_NODE_DEFAULT=$(command -v node); fi
fi
PS_NODE="${PI_SPOKE_NODE:-$PS_NODE_DEFAULT}"
if [[ ! -x "$PS_NODE" ]]; then
  [[ "$PS_NODE" == "$PS_BASE/node-v24.15.0/bin/node" ]] || { warn "Choose an existing Node binary or the offered install path."; exit 1; }
  [[ ! -e "$PS_BASE/node-v24.15.0" && ! -L "$PS_BASE/node-v24.15.0" ]] || { warn "Node install directory exists but is incomplete; select another existing binary."; exit 1; }
  say "Downloading Node 24.15.0 into $PS_BASE/node-v24.15.0"
  PS_ARCHIVE="node-v24.15.0-$PS_PLATFORM-$PS_ARCH.tar.gz"
  curl --proto '=https' --tlsv1.2 --fail --location --show-error "https://nodejs.org/dist/v24.15.0/$PS_ARCHIVE" -o "$PS_TEMP/$PS_ARCHIVE"
  curl --proto '=https' --tlsv1.2 --fail --location --show-error "https://nodejs.org/dist/v24.15.0/SHASUMS256.txt" -o "$PS_TEMP/SHASUMS256.txt"
  PS_EXPECTED=$(awk -v name="$PS_ARCHIVE" '$2 == name {print $1}' "$PS_TEMP/SHASUMS256.txt")
  [[ "$PS_EXPECTED" =~ ^[a-f0-9]{64}$ ]] || { warn "No checksum found for the Node archive."; exit 1; }
  if command -v shasum >/dev/null 2>&1; then PS_ACTUAL=$(shasum -a 256 "$PS_TEMP/$PS_ARCHIVE"); else PS_ACTUAL=$(sha256sum "$PS_TEMP/$PS_ARCHIVE"); fi
  [[ "${PS_ACTUAL%% *}" == "$PS_EXPECTED" ]] || { warn "Node archive checksum mismatch."; exit 1; }
  mkdir -p "$PS_BASE"
  PS_NODE_STAGE=$(mktemp -d "$PS_BASE/.node-install.XXXXXX")
  # Extract beside the final path so activation is one rename on the same filesystem.
  if ! tar -xzf "$PS_TEMP/$PS_ARCHIVE" -C "$PS_NODE_STAGE" --strip-components=1; then
    rm -rf -- "$PS_NODE_STAGE"; exit 1
  fi
  mv "$PS_NODE_STAGE" "$PS_BASE/node-v24.15.0"
fi
[[ "$("$PS_NODE" --version)" == v24.15.0 ]] || { warn "Use the qualified Node version 24.15.0."; exit 1; }
PS_NODE=$("$PS_NODE" -p 'process.execPath')
write_env PS_NODE "$PS_NODE" >/dev/null
export PATH="$(dirname -- "$PS_NODE"):$PATH"
PS_RUNTIME_DEFAULT="$PS_BASE/current"
PS_RUNTIME="${PI_SPOKE_INSTALL_DIR:-$PS_RUNTIME_DEFAULT}"
write_env PS_RUNTIME "$PS_RUNTIME" >/dev/null
[[ "$PS_RUNTIME" == /* ]] || { warn "Use an absolute installation path."; exit 1; }
if [[ -f "$PS_RUNTIME/dist/cli.js" && -d "$PS_RUNTIME/node_modules" ]]; then
  say "Using the existing installation: $PS_RUNTIME"
else
  say "Installing pi-spoke into $PS_RUNTIME with locked dependencies."
  mkdir -p "$(dirname -- "$PS_RUNTIME")"
  "$PS_NODE" "$PS_HELPER" install "$PS_SOURCE" "$PS_RUNTIME"
  PS_NPM="$(dirname -- "$PS_NODE")/npm"
  [[ -x "$PS_NPM" ]] || { warn "npm must be installed beside the selected Node binary."; exit 1; }
  (cd -- "$PS_RUNTIME" && "$PS_NPM" ci --ignore-scripts && "$PS_NPM" run build)
fi

stage "Workspace and defaults"
PS_CONFIG_DIR="${PI_SPOKE_CONFIG_DIR:-$HOME/.config/pi-spoke}"
[[ "$PS_CONFIG_DIR" == /* ]] || { warn "Use an absolute PI_SPOKE_CONFIG_DIR."; exit 1; }
cp "$ENV_FILE" "$PS_TEMP/install.env"
"$PS_NODE" "$PS_HELPER" defaults "$PS_CONFIG_DIR" "$ENV_FILE"
cat "$PS_TEMP/install.env" >> "$ENV_FILE"
load_answers
PS_INSTANCE="${PI_SPOKE_INSTANCE:-codex}"
write_env PS_INSTANCE "$PS_INSTANCE" >/dev/null
if [[ -f "$PS_CONFIG_DIR/config.json" ]]; then
  say "Existing permissions, limits, and model settings will be retained."
fi
say "Choose an existing workspace outside the installation and private configuration directories."
while :; do
  ask PS_WORKSPACE "Workspace${PS_WORKSPACE:+ [$PS_WORKSPACE]}:"
  [[ -n "$PS_WORKSPACE" ]] && break
  warn "A workspace is required. Ctrl-C exits."
done
write_env PS_WORKSPACE "$PS_WORKSPACE" >/dev/null
if [[ -n "$PS_PI_DIR" ]]; then
  say "Found Pi configuration: $PS_PI_DIR"
  say "Loading reuses Pi's credential/model files and replaces the pi-spoke model allowlist with Pi's catalog."
  if confirm "Load your Pi configuration?"; then
    PS_LOAD_PI=yes
    write_env PS_LOAD_PI "$PS_LOAD_PI" >/dev/null
  fi
fi
"$PS_NODE" "$PS_HELPER" prepare "$ENV_FILE" "$PS_TEMP"
PS_CODEX=$(command -v codex || true)
if [[ -z "$PS_CODEX" && -x /Applications/ChatGPT.app/Contents/Resources/codex ]]; then PS_CODEX=/Applications/ChatGPT.app/Contents/Resources/codex; fi
PS_CONNECT=no
if [[ "${PI_SPOKE_CODEX:-1}" != 0 && -n "$PS_CODEX" ]]; then
  PS_CONNECT=yes
  say "Codex: register pi_spoke after verification, replacing its entry with a configuration backup."
else
  say "Host connection: use the generated codex.toml snippet."
fi
say "Verification runs disposable sandbox and MCP checks without contacting providers."
if [[ "$PS_CONNECT" == yes ]]; then
  confirm "Save these settings, verify, and connect Codex?" || exit 0
else
  confirm "Save these settings and verify?" || exit 0
fi
"$PS_NODE" "$PS_HELPER" save "$PS_TEMP/plan.json"
PS_CONFIG_PATH="$PS_CONFIG_DIR/config.json"

stage "Verify and connect"
"$PS_NODE" "$PS_RUNTIME/dist/cli.js" doctor --config "$PS_CONFIG_PATH" --instance "$PS_INSTANCE"
PS_CHECKS_OK=yes
if ! "$PS_NODE" "$PS_RUNTIME/dist/cli.js" doctor --config "$PS_CONFIG_PATH" --instance "$PS_INSTANCE" --sandbox-check; then
  PS_CHECKS_OK=no
  SKIPPED+=("Sandbox verification failed; inspect docs/compatibility.md before running workers.")
fi
if ! "$PS_NODE" "$PS_HELPER" check "$PS_TEMP/plan.json"; then
  PS_CHECKS_OK=no
  SKIPPED+=("MCP handshake failed; inspect the installation and retry.")
fi
if [[ "$PS_CONNECT" == yes && "$PS_CHECKS_OK" == yes ]]; then
  PS_CODEX_CONFIG="${CODEX_HOME:-$HOME/.codex}/config.toml"
  if [[ -f "$PS_CODEX_CONFIG" ]]; then
    PS_CODEX_BACKUP=$(mktemp "$PS_CODEX_CONFIG.backup-XXXXXX")
    cat "$PS_CODEX_CONFIG" > "$PS_CODEX_BACKUP"
    say "Codex configuration backup: $PS_CODEX_BACKUP"
  fi
  "$PS_CODEX" mcp add pi_spoke -- "$PS_NODE" "$PS_RUNTIME/dist/cli.js" serve --config "$PS_CONFIG_PATH" --instance "$PS_INSTANCE"
  say "Codex connected. Restart Codex to load the connection."
else
  say "Connection snippet: $PS_CONFIG_DIR/codex.toml"
  if [[ "$PS_CONNECT" == yes ]]; then SKIPPED+=("Codex registration was skipped because verification failed."); fi
fi
say "Operator configuration: $PS_CONFIG_PATH"
if [[ "$PS_LOAD_PI" == yes ]]; then
  say "Pi configuration loaded. Restart Codex to use its model catalog."
else
  say "Model setup and changes: README.md → Model configuration."
fi
say "Guide: $PS_RUNTIME/README.md"
if (( ${#SKIPPED[@]} )); then
  warn "Setup saved with remaining steps:"
  for PS_ITEM in "${SKIPPED[@]}"; do say "$PS_ITEM"; done
else
  say "Installation complete. Model configuration and provider access are checked separately."
fi
